name: gnn_efficiency
channels:
  - default
dependencies:
  - python=3.8
  - numpy>=1.10.0
  - pandas>=1
  - matplotlib
  - scikit-learn
  - tqdm
  - numba
  - pylint
  - pytest
  - loguru
  - memory_profiler
  - pyarrow=7
  - tensorboard
  - conda-forge::uproot=4.1.8
  - dglteam::dgl-cuda11.3
  - pytorch::pytorch=1.10.2=py3.8_cuda11.3_cudnn8.2.0_0
  - cudatoolkit
  - natsort
